# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

def shared_pods
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for algois.me
    
    pod 'common', :path => '../common'
    pod 'Alamofire', '~> 4.9.1'
    pod 'TinyConstraints'
    pod 'SDWebImage', '~> 5.0'
    pod 'SDWebImageSwiftUI', '~> 2.0'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'
    pod 'PKHUD', '~> 5.0'
    pod 'Toast-Swift', '~> 5.0.1'
    pod 'Charts'
    pod 'Firebase/Auth'
    pod 'Firebase/Messaging'
    
end

target 'algois.me Debug' do
    shared_pods
end

target 'algois.me Release' do
    shared_pods
end
