name: algois-me
options:
  createIntermediateGroups: true
  indentWidth: 4
  tabWidth: 4
settings:
  base:
    MARKETING_VERSION: 2.1.0
    CURRENT_PROJECT_VERSION: 43
configs:
  Debug: debug
  integ: debug
  test: debug
  Release: release
targets:
  "algois.me Release":
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:  
      - path: "algois-me"
        excludes:
          - "Firebase"
      - path: "algois-me/Firebase/Release"
    scheme: 
      testTargets:
        - "algois.me Tests"
        - "algois.me UITests"
      gatherCoverageData: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "io.xorum.codeforceswatcher"
        PRODUCT_NAME: "algois.me"
    postBuildScripts:
      - name: "[Firebase Crashlytics] Run"
        script: '"${PODS_ROOT}/FirebaseCrashlytics/run"'
        inputFiles:
          - "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}"
          - "$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)"
    entitlements:
      path: "algois-me/MyEntitlements.entitlements"
      properties:
        aps-environment: development
  "algois.me Debug":
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: "algois-me"
        excludes:
          - "Firebase"
      - path: "algois-me/Firebase/Debug"
    scheme:
      testTargets:
        - "algois.me Tests"
        - "algois.me UITests"
      gatherCoverageData: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "io.xorum.codeforceswatcher.debug"
        PRODUCT_NAME: "algois.me Debug"
    postBuildScripts:
      - name: "[Firebase Crashlytics] Run"
        script: '"${PODS_ROOT}/FirebaseCrashlytics/run"'
        inputFiles:
          - "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}"
          - "$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)"
    entitlements:
      path: "algois-me/MyEntitlements.entitlements"
      properties:
        aps-environment: development
  "algois.me Tests":
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: "algois-me Tests"
    dependencies:
      - target: "algois.me Debug"
    scheme:
      gatherCoverageData: false
  "algois.me UITests":
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: "algois-me UITests"
    dependencies:
      - target: "algois.me Debug"
    scheme:
      gatherCoverageData: false
